### ISSUE TITLE
Remove jinja variable for SHA256 in meta.yaml

### ISSUE THREAD

**Issue by bobleesj** [conda-forge/diffpy.utils-feedstock#32]
### Comment:

As recommended by https://github.com/conda-forge/staged-recipes/pull/27265/files#r1736210779

**Comment by sbillinge** [comment]
What is the question?

**Comment by bobleesj** [comment]
Please disregard the `question` label. The issue template provides three options: 1) Bug report, 2) Bot commands, and 3) General question. I believe it was automatically added.

Could you please remove the label?

**Comment by bobleesj** [comment]
Resolved: https://github.com/conda-forge/diffpy.utils-feedstock/pull/38
